import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Index() {

    return <div className={styles.container}>
      <Head>
        <title>revingtron boiler plate</title>
        <meta name="description" content="Generated by revingtron" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Revingtron Boiler Plate</h1>
      <p>
        this is a boiler plate generated by revingtron
        to efficiently build web apps from scratch using next.js</p>
</div>;
}
